/-
Range-analysis support tactics for BVModEq.

This file contains the implementation of `try_apply_lemma_hyps`, a tactic
that attempts to discharge arithmetic range side goals generated by the
BitVec/ZMod translation pipeline. It combines local rewriting, `valify`,
`bvify`, mux factoring, lightweight case splitting, and applications of
standard range lemmas.
-/

import Lean
import Lean.Elab.Tactic.Basic
import Lean.Meta.Basic
import Lean.Parser.Tactic

import Mathlib.Algebra.Field.ZMod
import Mathlib.Control.Monad.Cont
import Mathlib.Data.Nat.Basic
import Mathlib.Tactic
import Mathlib.Tactic.Eval

import BVModEq.Lemmas
import BVModEq.Valify
import BVModEq.BVify

open Lean Meta Elab Tactic
open Lean.Parser.Tactic

namespace BVModEq

/-- Build a nested `Nat.add` expression from a list of terms. -/
def mkAddNat (es : List Expr) : Expr :=
  match es with
  | []      => mkNatLit 0
  | [e]     => e
  | e :: es => mkApp2 (mkConst ``Nat.add) e (mkAddNat es)

set_option linter.unusedVariables false

/-- Rebuild a factored mux expression as `(1 - x) * sumB + x * sumA`. -/
def rebuild (x sumA sumB : Expr) : MetaM Expr := do
  let one       := mkNatLit 1
  let oneMinusX := mkApp2 (mkConst ``Nat.sub) one x
  let term1     := mkApp2 (mkConst ``Nat.mul) x sumA
  let term2     := mkApp2 (mkConst ``Nat.mul) oneMinusX sumB
  let res       := mkApp2 (mkConst ``Nat.add) term2 term1
  return res

/-- Check whether an expression contains any metavariable. -/
partial def containsMVar (e : Expr) : Bool :=
  match e with
  | .mvar _ => true
  | .app f x => containsMVar f || containsMVar x
  | _ => false

/--
Recognize sums of mux-shaped products.

For an expression like `x * A + (1 - x) * B + x * C`, this returns
`some (x, [A, C], [B])`.
-/
partial def viewAsMux (e : Expr) : Option (Expr × List Expr × List Expr) := do
  match e.getAppFnArgs with
  | (``HAdd.hAdd, #[_, _, _, _, lhs, rhs])  => do
    let (lv, las, lbs) ← viewAsMux lhs
    let (rv, ras, rbs) ← viewAsMux rhs
    if (lv != rv) then none
    (lv, las ++ ras, lbs ++ rbs)
  | (``HMul.hMul, #[_, _, _, _, lhs, rhs]) =>
    match lhs.getAppFnArgs with
    | (``HSub.hSub, #[_, _, _, _, _, subRHS]) => some (subRHS, [], [rhs])
    | _ => some (lhs, [rhs], [])
  | _ => none

/--
Case split two hypotheses known to be Boolean-valued naturals, then simplify
each of the four resulting cases.
-/
elab "elim2_norm_num" h1:ident h2:ident : tactic => do
  let id1 : TSyntax `ident := mkIdent h1.getId
  let id2 : TSyntax `ident := mkIdent h2.getId
  evalTactic (← `(tactic| apply split_one at $(id1):ident))
  evalTactic (← `(tactic| apply split_one at $(id2):ident))
  evalTactic (← `(tactic| apply Or.elim $id1))
  evalTactic (← `(tactic| intro hx; apply Or.elim $id2))
  evalTactic (← `(tactic| intro hy; rewrite [hx]; rewrite [hy]; simp;))
  evalTactic (←  `(tactic| try apply Nat.le_refl))
  evalTactic (←  `(tactic| try rfl))
  evalTactic (← `(tactic| intro hy; rewrite [hy]; rewrite [hx]; simp;))

  evalTactic (←  `(tactic|try apply Nat.le_refl))
  evalTactic (←  `(tactic| try rfl))
  evalTactic (← `(tactic| intro hx; apply Or.elim $id2))
  evalTactic (← `(tactic| intro hy; rewrite [hx]; rewrite [hy]; simp;))

  evalTactic (←  `(tactic|try apply Nat.le_refl))
  evalTactic (←  `(tactic|try rfl))
  evalTactic (← `(tactic| intro hy; rewrite [hy]; rewrite [hx]; simp;))
  evalTactic (←  `(tactic|try apply Nat.le_refl))
  evalTactic (←  `(tactic| try rfl))

/-- Determines if any expression contains a subtraction in its arguments, recursively.  Does not go
under the indexing part of a vector indexing expression. -/
partial def containsSub (e : Expr) :  MetaM Bool := do
  if not e.isApp then return false
  match e.getAppFnArgs with
  | (``HSub.hSub, _) => return true
  | (``getElem, #[_,_,_,_,_, vectorExpr, _, _]) => containsSub vectorExpr
  | (_, args) => args.anyM containsSub

/-- Check whether the expression is headed by an inequality relation. -/
def isIneq (e : Expr) : Bool :=
  match e.getAppFn.constName? with
  | some n =>
      n == ``LE.le || n == ``LT.lt || n ==``GT.gt || n ==``GE.ge
  | none => false

/-- Check whether the expression is headed by an arithmetic operator. -/
def isArithmeticHead (e : Expr) : Bool :=
  match e.getAppFn.constName? with
  | some n =>
      n == ``HAdd.hAdd || n == ``Add.add ||
      n == ``HSub.hSub || n == ``Sub.sub ||
      n == ``HMul.hMul || n == ``Mul.mul ||
      n == ``Neg.neg   || n == ``HMod.hMod ||
      n == ``HPow.hPow || n == ``Pow.pow || n == ``ite
  | none => false

private def compositeInsideValHere? (e : Expr) : MetaM Bool := do
  if e.isAppOf ``ZMod.val then
    let args := e.getAppArgs
    if let some t := args.back? then
      if isArithmeticHead t then

        return true
  return false

/-- DFS for first subterm of the form `ZMod.val t` where `t` is composite
(arithmetic-headed). -/
partial def firstCompositeInsideVal? (e : Expr) : MetaM Bool := do
  if (← compositeInsideValHere? e) then
    return true
  match e with
  | .app f a =>
      if (← firstCompositeInsideVal? f ) then return true
      return ← firstCompositeInsideVal? a
  | _ =>
    return false

/-- Recurses through the expression to find all free variables that appear in it, either as is, or
as part of some vector indexing operation. -/
partial def collectTerms (e : Expr) : MetaM NameSet := do
  let lctx ← getLCtx
  let e <- instantiateMVars e

  if e.isFVar then
    if let some decl := lctx.find? e.fvarId! then
      return {decl.userName}
  if e.isApp then
    let (fn, args) := e.getAppFnArgs

    match (fn, args) with
    | (``getElem, #[_,_,_,_,_, vectorExpr, indexExpr, _]) =>
      if vectorExpr.isFVar then
        if let some decl := lctx.find? vectorExpr.fvarId! then
          let idxPretty ← PrettyPrinter.ppExpr indexExpr

          return {Name.mkSimple s!"{decl.userName}[{idxPretty}]"}
      if vectorExpr.isApp then
        let (fn1, args1) := vectorExpr.getAppFnArgs
          match (fn1, args1) with
          | (``ite, _) =>
              return {Name.mkSimple s!"{args1[4]!}"} ++ {Name.mkSimple s!"{args1[3]!}"} ++ {Name.mkSimple s!"{args1[2]!}" }
          | _ =>
            let idxPretty ← PrettyPrinter.ppExpr indexExpr
            return {Name.mkSimple s!"{vectorExpr}[{idxPretty}]"}
    | _ =>
      return (← args.mapM collectTerms).foldl (· ++ ·) {}
  if e.isMData then
      return (← collectTerms e.mdataExpr!)
  return {}

/-- Count subtraction nodes in an expression. -/
partial def countMinusOps (e : Expr) : Nat :=
  if e.isAppOfArity ``HSub.hSub 2 then
    let args := e.getAppArgs
    let a := args[0]!
    let b := args[1]!
    1 + countMinusOps a + countMinusOps b
  else
    match e with
    | .app f x => countMinusOps f + countMinusOps x
    | .lam _ _ body _ => countMinusOps body
    | .letE _ t v b _ => countMinusOps t + countMinusOps v + countMinusOps b
    | .proj _ _ e => countMinusOps e
    | _ => 0

/-- Check whether an expression contains a modulus operator. -/
partial def exprHasMod (e : Expr) : Bool :=
  match e with
  | .app f a =>
      exprHasMod f || exprHasMod a
  | .lam _ _ body _ =>
      exprHasMod body
  | .forallE _ _ body _ =>
      exprHasMod body
  | .letE _ _ val body _ =>
      exprHasMod val || exprHasMod body
  | .mdata _ b =>
      exprHasMod b
  | .proj _ _ b =>
      exprHasMod b
  | .const n _ =>
      n == ``HMod.hMod || n == ``Mod.mod
  | _ => false

/-- Check whether an expression contains an `if`. -/
partial def exprHasIf (e : Expr) : Bool :=
  match e with
  | .app f a =>
      exprHasIf f || exprHasIf a
  | .lam _ _ body _ =>
      exprHasIf body
  | .forallE _ _ body _ =>
      exprHasIf body
  | .letE _ _ val body _ =>
      exprHasIf val || exprHasIf body
  | .mdata _ b =>
      exprHasIf b
  | .proj _ _ b =>
      exprHasIf b
  | .const n _ =>
      n == ``ite || n == ``dite
  | _ => false

/-- Check whether an expression contains an `if` inside another `if`. -/
partial def exprHasNestedIf (e : Expr) : Bool :=
  match e with
  | .app f a =>
     match f with
      | .const n _ =>
        if n == ``ite || n == ``dite then

            if exprHasIf a.getAppArgs[a.getAppArgs.size-3]! ||
               exprHasIf a.getAppArgs[a.getAppArgs.size-2]! ||
               exprHasIf a.getAppArgs[a.getAppArgs.size-1]! then
              true
            else false
        else false
      | _ => exprHasIf a
  | .lam _ _ body _ =>
      exprHasIf body
  | .forallE _ _ body _ =>
      exprHasIf body
  | .letE _ _ val body _ =>
      exprHasIf val || exprHasIf body
  | .mdata _ b =>
      exprHasIf b
  | .proj _ _ b =>
      exprHasIf b
  | .const n _ =>
      n == ``ite
  | _ => false

syntax (name := tryApplyLemHyps) "try_apply_lemma_hyps" ppSpace "[" ident,* "]" : tactic

/-- Simplify the proof obligations introduced by mux factoring. -/
def didMux : TacticM Unit := do
  evalTactic (← `(tactic| try simp))
  evalTactic (← `(tactic| try ring))
  evalTactic (← `(tactic| try intro hMux))
  evalTactic (← `(tactic| try simp only [hMux]))
  evalTactic (← `(tactic| try simp ))
  evalTactic (← `(tactic| rw [Nat.mux_if_then] at ⊢))

/-- Check whether both sides of a binary expression are arithmetic-headed expressions. -/
def bothArgsAreApps (e : Expr) : Bool :=
  match e.getAppFnArgs with
  | (_, #[_,_, lhs, rhs]) =>
      isArithmeticHead lhs && isArithmeticHead rhs
  | _ => false

/-- Result returned by one focused-goal pass of the main tactic loop. -/
structure LoopBodyResult where
  didMux : Bool
  madeProgress : Bool
  goals : List MVarId
  leftSide: Bool
  stopCompletely : Bool

def LoopBodyLabel := MonadCont.Label LoopBodyResult (ContT LoopBodyResult TacticM) Unit

/-- Detect and factor mux-shaped arithmetic, adding the factored equality as a hypothesis. -/
def handleIfMux (loopBodyReturn : LoopBodyLabel) (g : MVarId) (args : Array Expr)
  : ContT LoopBodyResult TacticM Unit := do
  match viewAsMux args[2]! with
  | some (x, lhs@(_ :: _), rhs@(_ :: _)) =>
    let a := mkAddNat lhs
    let b := mkAddNat rhs
    let finalExpr ← monadLift $ g.withContext (rebuild x a b)
    let prop ← mkEq args[2]! finalExpr
    let pr ← mkFreshExprMVar prop
    let gWithHyp ← g.assert `hMux prop pr
    setGoals [pr.mvarId!, gWithHyp]
    didMux
    let MyGoals <- getGoals
    loopBodyReturn.apply { didMux := false, madeProgress := true, goals := MyGoals, leftSide := false, stopCompletely := false}
  | _ => return ()

/-- Return the number of collected terms that correspond to BitVec variables. -/
def checkTermsAreBitVecs (g : MVarId) (terms : NameSet) : MetaM Nat:=
  g.withContext do
    let lctx ← getLCtx
    let locals := lctx.getFVarIds.map (fun id => lctx.get! id)
    let mut bitVecCount := 0

    for n in terms.toList do
      let rawStr := n.toString
      let baseStr := rawStr.takeWhile (· != '[')
      let cleanStr := (baseStr.trim.replace "«" "" |>.replace "»" "")

      match locals.findSome? (fun d =>
        let uname := d.userName.toString
        if uname == cleanStr || uname.endsWith cleanStr then some d else none) with
      | none =>

        logInfo m!"try_apply_lemma_hyps: variable {cleanStr} was not found in the local context (locals: {locals.map (·.userName)})"
        return 200000
      | some decl =>
        let t ← whnf decl.type
        match t.getAppFnArgs with
        | (``BitVec.toNat, #[_]) => return 0
        | (``ZMod, #[_]) => return 0
        | (``BitVec, #[_]) =>
          bitVecCount := bitVecCount + 1
        | (``Vector, #[ty, len]) =>
            match ty.getAppFnArgs with
                | (``ZMod, #[_]) => return 0
                | (``BitVec, #[_]) => bitVecCount := bitVecCount + 1
                | _ => return 0
        | _ =>
          logInfo m!"try_apply_lemma_hyps: term has non-BitVec type {t}; skipping BitVec case split"
          return 0
    return  bitVecCount

def isBitVecType (ty : Expr) : Bool :=
  match ty.getAppFn with
  | .const ``BitVec _ => true
  | _ => false

/-- Case split on collected indexed BitVec variables. -/
def caseSplitOnBitVecNames (g : MVarId) (terms : NameSet) : TacticM (List MVarId) :=
  g.withContext do
    let lctx ← getLCtx
    let names := terms.toList

    for idx in [0:names.length] do
      let n := names[idx]!
      let s := n.toString.trim.replace "«" "" |>.replace "»" ""
      if ! (s.contains '[') then
        return []
      let (base, idxStr) :=
        match s.splitOn "[" with
        | [v, rest] => (v.trim, rest.takeWhile (·.isDigit))
        | _ => (s, "0")

      let some idxNat := idxStr.toNat?
        | logInfo m!"try_apply_lemma_hyps: could not parse BitVec index in {s}"; continue

      match lctx.findFromUserName? (Name.mkSimple base) with
      | none => logInfo m!"try_apply_lemma_hyps: variable {base} was not found in the local context"
      | some decl =>
        let t ← whnf decl.type
        match t.getAppFnArgs with
        | (``BitVec, #[_]) => do
          let tacticStx ←
            `(tactic| cases h : $(mkIdent (Name.mkSimple base))[$(Quote.quote idxNat)])
          evalTactic tacticStx

          if idx == names.length - 1 then
            let mut progress := true
            while progress do
              try
                let gs <- getGoals
                if gs.isEmpty then
                  return gs
                evalTactic (← `(tactic| simp))
              catch _ => progress := false

            evalTactic tacticStx

        | _ =>
          logInfo m!"try_apply_lemma_hyps: {base} is not a BitVec variable; skipping case split"

    getGoals

/--
When a goal depends on exactly two Boolean-valued terms, split into cases
instead of relying only on monotonicity/range lemmas.
-/
def caseByCaseOnTwoVariables (loopBodyReturn : LoopBodyLabel)
  (g : MVarId) (hyps : List Name) (terms : NameSet)
  : ContT LoopBodyResult TacticM Unit := do
  let m <- checkTermsAreBitVecs g terms
  if (m==0)  then
    let bounds ← monadLift $ g.withContext do
      let lctx ← getLCtx
      hyps.foldlM (init := []) fun acc hName => do
        let some decl := lctx.findFromUserName? hName
          | throwError m!"try_apply_lemma_hyps: could not find a hypothesis named `{hName}`"
        match decl.type.getAppFnArgs with
        | (``LE.le, #[_, _, lhs, rhs]) =>
          match (← whnf rhs) with
          | (Expr.lit (Literal.natVal 1)) => do
            let LHSvars ← collectTerms lhs
            let varsList := LHSvars.toList
            if LHSvars.size == 1 && terms.contains varsList[0]! then
              return decl :: acc
            else
              return acc
          | _ => return acc
        | _ => return acc
    if bounds.length = 2 then
      monadLift $ withMainContext do
        let h1 := mkIdent  bounds[0]!.userName
        let h2 := mkIdent  bounds[1]!.userName
        evalTactic (← `(tactic| try focus elim2_norm_num $h1 $h2))
      if ← g.isAssigned then
        if (← getUnsolvedGoals).contains g then
          logInfo m!"try_apply_lemma_hyps: elim2_norm_num made progress on goal {g}, but did not fully solve it"
        else

          loopBodyReturn.apply { didMux := false, madeProgress := true, goals := [], leftSide:= false, stopCompletely := false }
      else
         return ()
  else if (m == 2 ) then
        let newGoals ← caseSplitOnBitVecNames g terms
        if ← g.isAssigned then
          if (← getUnsolvedGoals).contains g then
            logInfo m!"try_apply_lemma_hyps: elim2_norm_num made progress on goal {g}, but did not fully solve it"
            loopBodyReturn.apply { didMux := false, madeProgress := true, goals := [g], leftSide:= false, stopCompletely:= false }
          else
            loopBodyReturn.apply { didMux := false, madeProgress := true, goals := newGoals, leftSide:= false, stopCompletely:= false }
      else
         return ()

syntax (name := splitPropIf) "split_prop_if " term : tactic

macro_rules
  | `(tactic| split_prop_if $p) =>
      `(tactic|  by_cases h : $p <;> try simp [h] at *)

/-- Split an `if` condition and simplify the resulting branches. -/
def applyIfLemma (loopBodyReturn : LoopBodyLabel) (cond0: Expr): ContT LoopBodyResult TacticM Unit := do
  let decTy ← Meta.inferType cond0
  try
    if (decTy.getAppApps.size != 0) then
      let g <- getMainGoal
      let condSyn ← monadLift <| Lean.Elab.Term.exprToSyntax decTy.getAppArgs[0]!
      monadLift $ do evalTactic (← `(tactic| split_prop_if $condSyn))
      let g' <- getMainGoal
      let t  ← (← g.getType)  |> instantiateMVars
      let t' ← (← g'.getType) |> instantiateMVars
      if t == t' then
         monadLift $ do evalTactic (← `(tactic| split_ifs))
      loopBodyReturn.apply { didMux := false, madeProgress := true, goals := (← getGoals), leftSide := false, stopCompletely:= false}
    else
      monadLift $ do evalTactic (← `(tactic| split_ifs))
      loopBodyReturn.apply { didMux := false, madeProgress := true, goals := (← getGoals), leftSide := false, stopCompletely:= false }
  catch _ =>
    try
      monadLift $ do evalTactic (← `(tactic| focus split_ifs with h <;> simp [*]))
      loopBodyReturn.apply { didMux := false, madeProgress := true, goals := (← getGoals), leftSide := false, stopCompletely:= false }
    catch e =>
      logInfo (Lean.Exception.toMessageData e)
      pure ()

/-- Apply a candidate lemma to the focused goal and return its generated subgoals. -/
def applyThisLemma (loopBodyReturn : LoopBodyLabel) (g : MVarId) (goalType : Expr) (leftSide : Bool) (stx : Syntax)

  : ContT LoopBodyResult TacticM Unit := do
  try
    let subgoals ← g.apply (← elabTerm stx goalType)
    loopBodyReturn.apply { didMux := false, madeProgress := true, goals := subgoals,  leftSide := leftSide, stopCompletely:= false }
  catch _ =>
    pure ()

/-- Try `Nat.le_refl`; if it is not applicable, fall back to the provided lemma. -/
def applyNatLeRefl2
    (loopBodyReturn : LoopBodyLabel) (g : MVarId) (goalType : Expr)
    (leftSide : Bool) (stx : Syntax) :
    ContT LoopBodyResult TacticM Unit := do
  try
    let subgoals ← withMainContext do
      let goalType ← instantiateMVars (← g.getType)
      let (fn, args) := goalType.getAppFnArgs
      match fn with
      | ``LE.le =>
          let a := args[args.size - 1]!
          let b := args[args.size - 2]!
          let a ← instantiateMVars a
          match (← whnf a) with
          | Expr.lit (Literal.natVal _) =>
              g.apply (mkApp (mkConst ``Nat.le_refl) a)
          | _ =>
              let b ← instantiateMVars b
              match (← whnf b) with
              | Expr.lit (Literal.natVal _) =>
                  g.apply (mkApp (mkConst ``Nat.le_refl) b)
              | _ =>
                  throwError "not a Nat.le goal solved by reflexivity"
      | _ =>
          throwError "not a Nat.le goal"
    loopBodyReturn.apply {
      didMux := false,
      madeProgress := true,
      goals := subgoals,
      leftSide := leftSide,
      stopCompletely := false
    }
  catch _ =>
    applyThisLemma loopBodyReturn g goalType leftSide stx

/--
Try ZMod-specific progress: apply relevant hypotheses, simplify using them
backwards, run `valify`, and finally fall back to the `.val` upper-bound lemma.
-/
def applyZModLemma (loopBodyReturn : LoopBodyLabel) (g : MVarId) (goalType : Expr) (leftSide : Bool) (hyps : List Name)
  : ContT LoopBodyResult TacticM Unit := do
  for hName in hyps do
    try
      let subgoals ← monadLift $ g.withContext do
        let lctx ← getLCtx
        let some decl := lctx.findFromUserName? hName
          | throwError m!"try_apply_lemma_hyps: could not find a hypothesis named `{hName}`"
        g.apply (mkFVar decl.fvarId)
      return (← loopBodyReturn.apply { didMux := false, madeProgress := true, goals := subgoals , leftSide := false, stopCompletely:= false})
      catch _err => pure ()
    try

      let hypSyn <- monadLift $ g.withContext do
        let lctx1 ← getLCtx
        let some decl := lctx1.findFromUserName? hName
          | throwError m!"try_apply_lemma_hyps: could not find a hypothesis named `{hName}`"
        let hypExpr : Expr := mkFVar decl.fvarId
        let hypSyn ←  Lean.Elab.Term.exprToSyntax hypExpr
        return hypSyn
      monadLift $ do evalTactic  (← `(tactic| simp [← $hypSyn] ))
      let subgoals ← getGoals
      return (← loopBodyReturn.apply { didMux := false, madeProgress := true, goals := subgoals , leftSide := false, stopCompletely:= false})

    catch _ => pure ()
  try
       monadLift $ do evalTactic  (← `(tactic| valify [] ))
       let subgoals ← getGoals
       return (← loopBodyReturn.apply { didMux := false, madeProgress := true, goals := subgoals , leftSide := false, stopCompletely:= false})
  catch e =>
      try
         monadLift $ do evalTactic  (← `(tactic| simp))
         let subgoals ← getGoals
         return (← loopBodyReturn.apply { didMux := false, madeProgress := true, goals := subgoals , leftSide := false, stopCompletely:= false})
      catch _ =>
      pure ()

  let lt ← monadLift (m := TacticM) ``(ZMod.toNatLT)
  let applyThisLemma := applyThisLemma loopBodyReturn g goalType leftSide
  applyThisLemma lt

/-- Select and apply a range-analysis lemma based on the head symbol of the active side. -/
def findAndApplyRangeAnalysisLemma (loopBodyReturn : LoopBodyLabel)
  (terms : NameSet) (g : MVarId) (mainGoalType : Expr) (hyps : List Name)
  : ContT LoopBodyResult TacticM Unit := do
  let lt ← monadLift (m := TacticM) ``(Nat.lt_of_le_of_lt)

  let sub ← monadLift (m := TacticM) ``(Nat.lt_sub)
  let subL ← monadLift (m := TacticM) ``(Nat.gt_sub)
  let add ← monadLift (m := TacticM) ``(Nat.add_le_add)
  let mul ← monadLift (m := TacticM) ``(Nat.mul_le_mul)
  let bitvecLT ← monadLift (m := TacticM) ``(BitVec.toNatLT)
  let bitvecGT ← monadLift (m := TacticM) ``(BitVec.toNatGT)
  let zmodGT  ← monadLift (m := TacticM) ``(ZMod.toNatGT)
  let modLemma ← monadLift (m := TacticM) ``(mod_le_pred)
  let expLeq ← monadLift (m := TacticM) ``(Nat.le_trans)
  let constLeq ← monadLift (m := TacticM) ``(Nat.le_of_lt_add_one)
  let (fn, args) := mainGoalType.getAppFnArgs

  let mut leftSide := false

  if (!args[2]!.isApp  && args[3]!.isApp) || ( (<- collectTerms args[2]!).size == 0  && (<- collectTerms args[3]!).size != 0  ) then
    leftSide := true
  else
    leftSide := false
  let applyThisLemma := applyThisLemma loopBodyReturn g mainGoalType leftSide
  let unfolded ←  if !leftSide then
     monadLift $ withTransparency .reducible (whnf args[2]!)
  else
     monadLift $ withTransparency .reducible (whnf args[3]!)
  let fn3 := unfolded.getAppFn
  if (terms.size > 0) then
      match fn with

        | ``LT.lt =>
          match fn3 with
          | Expr.const name _ =>
            match name with
            | ``ite =>
                let iteArgs := unfolded.getAppArgs
                if iteArgs.size == 5 then
                    let cond := iteArgs[2]!
                    applyIfLemma loopBodyReturn cond
                  else
                    pure ()
            | ``OfNat.ofNat => pure ()
            | _ => applyThisLemma lt
          | _ => pure ()
        | _ => pure ()
      match fn with
        | ``LE.le =>
          if containsMVar mainGoalType then
            match fn3 with
              | Expr.const name _ =>
                match name with
                | ``HSub.hSub =>
                  if leftSide then
                      applyThisLemma subL
                  else
                      applyThisLemma sub
                | ``HAdd.hAdd => applyThisLemma add
                | ``HMul.hMul => applyThisLemma mul
                | ``HMod.hMod => applyThisLemma modLemma
                | ``ite =>

                    let iteArgs := unfolded.getAppArgs
                    if iteArgs.size == 5 then
                      let cond := iteArgs[2]!
                      applyIfLemma loopBodyReturn cond
                    else
                      pure ()
                | ``ZMod.val =>
                    if !leftSide then
                      applyZModLemma loopBodyReturn g mainGoalType leftSide hyps
                    else
                      applyThisLemma zmodGT
                | ``BitVec.toNat =>
                  if exprHasMod mainGoalType then
                    applyThisLemma modLemma
                  else
                    if !leftSide then
                      applyThisLemma bitvecLT
                    else
                      applyThisLemma bitvecGT
                | _ =>
                    pure ()
              | _ =>
                if fn3.isFVar then applyZModLemma loopBodyReturn g mainGoalType leftSide hyps

          else
                match fn3 with
                  | Expr.const name _ =>
                    match name with
                    | ``OfNat.ofNat => applyThisLemma constLeq
                    | ``ite   =>
                        let iteArgs := unfolded.getAppArgs
                          if iteArgs.size == 5 then
                            let cond := iteArgs[2]!
                            applyIfLemma loopBodyReturn cond
                          else
                            pure ()
                    | _ =>
                      if terms.size >= 1 then
                        applyThisLemma expLeq
                      else
                        pure ()
                  | _ =>
                  pure ()
        | _ =>
        pure ()

/--
Main range-analysis tactic. It repeatedly focuses one goal, normalizes it,
tries specialized BitVec/ZMod simplification, splits muxes/ifs when useful,
and applies range lemmas until no more progress is made.
-/
@[tactic tryApplyLemHyps]
elab_rules : tactic
| `(tactic| try_apply_lemma_hyps [$hs,*]) => do
  let hyps := (hs.getElems.map (·.getId)).toList
  let mut progress := true
  let mut need_to_valify :=false
  let mut sargs :
  Array (TSyntax [`Lean.Parser.Tactic.simpStar,
                        `Lean.Parser.Tactic.simpErase,
                        `Lean.Parser.Tactic.simpLemma]) := #[]
  for i in hs.getElems do
          let sa ← `(simpArg| $i:term)
          let ua :
          TSyntax [`Lean.Parser.Tactic.simpStar,
                  `Lean.Parser.Tactic.simpErase,
                  `Lean.Parser.Tactic.simpLemma] :=
          ⟨sa.raw⟩
          sargs := sargs.push ua
  evalTactic (← `(tactic| all_goals try rw [neg_add_to_sub]))
  evalTactic (← `(tactic| all_goals try rw [<- sub_eq_add_neg]))
  evalTactic (← `(tactic| all_goals try rw [neg_param]))
  evalTactic (← `(tactic| all_goals try rw [sub_add_right_recursive]))
  evalTactic (← `(tactic|  all_goals try simp [Nat.mul_assoc]))
  let mut sanity <- getGoals
  if sanity.isEmpty then
    return
  let mut cont := true
  let mut count  := 0
  while (cont ) do
    try
      evalTactic (← `(tactic| all_goals rw [Nat.mul_comm_ofNat]))
    catch _ =>
      cont := false
  evalTactic (← `(tactic| try all_goals simp [Nat.mul_assoc]))

  let mut did_mux := false
  let mut stop_completely := false
  count  := 0
  while (progress ) do
    count := count + 1
    if stop_completely then
      logInfo m!"try_apply_lemma_hyps: stopping because the focused goal is not an inequality"
      progress := false
      return
    if did_mux then do
      didMux
      did_mux := false
    let goals ← getGoals
    let mut updatedGoalsReversed : List MVarId := []
    let mut handled := false
    progress := false
    let mut goalQueue := Std.Queue.mk [] goals
    while (not handled && not goalQueue.isEmpty  ) do
      count := count + 1
      let mut some (g, rest) := goalQueue.dequeue? | unreachable!
      goalQueue := rest
      if (← g.isAssigned) then
        updatedGoalsReversed := g :: updatedGoalsReversed
        continue
      setGoals [g]
      let goalType ← g.getType
      let mut instantiatedGoalType ← instantiateMVars goalType

      let (fn, args) := instantiatedGoalType.getAppFnArgs

      let nonIneqGoal :=
        match fn with
        | ``LT.lt => false
        | ``LE.le => false
        | ``GT.gt => false
        | ``GE.ge => false
        | _ => true

      if nonIneqGoal then
        stop_completely := true
        let gs <- getGoals
        updatedGoalsReversed := gs ++ updatedGoalsReversed
        continue
      let terms ← collectTerms instantiatedGoalType
      let i := countMinusOps instantiatedGoalType
      if (<- firstCompositeInsideVal? instantiatedGoalType) ||  need_to_valify then do
        try
          evalTactic (← `(tactic| valify [$sargs,*]))
          evalTactic (← `(tactic| try simp))
          let gs <- getGoals
          updatedGoalsReversed := gs ++ updatedGoalsReversed
          progress := true
          handled := true
        catch _ =>
            pure ()
        if i > 0 then
          try
            evalTactic (← `(tactic| try valify [$sargs,*]))
            evalTactic (← `(tactic| rw [ZMod.val_sub]))
            evalTactic (← `(tactic| try valify [$[$sargs],*] ) )
            evalTactic (← `(tactic| try rw  [Nat.mod_eq_of_lt]))
            evalTactic (← `(tactic| try simp))
            let gs <- getGoals
            updatedGoalsReversed := gs ++ updatedGoalsReversed
            progress := true
            handled := true
            continue
          catch  e =>
               pure ()

      else
        if isBitVecType instantiatedGoalType then do
          try
            if i == 0 then
              evalTactic (← `(tactic| bvify [$sargs,*]))
            for _ in [:i] do
                evalTactic (← `(tactic|  rw [Mathlib.Tactic.BVify.BitVec.ofNat_sub]))
                evalTactic (← `(tactic| try bvify [$[$sargs],*] ) )
            let gs <- getGoals
            updatedGoalsReversed := gs ++ updatedGoalsReversed
            progress := true
            handled := true
            continue
            catch  _ =>
              handled :=true
              progress := false
              let gs <- getGoals
              updatedGoalsReversed := gs ++ updatedGoalsReversed
      let terms0 ← collectTerms instantiatedGoalType
      if !progress && exprHasMod instantiatedGoalType && !(terms0.size == 0) then
        try

          evalTactic (← `(tactic| rw [Nat.mod_eq_of_lt]))
              let cur_g ← getGoals
              match cur_g with
              | [] =>
                  throwError "try_apply_lemma_hyps: no goals remained after Nat.mod_eq_of_lt"
              | g_one :: []  =>
                  evalTactic (← `(tactic| try_apply_lemma_hyps [$[$hs],*]))

                  let after ← getGoals

                  if after.isEmpty then
                    progress := true
                    handled := true
                    let gs <- getGoals
                    updatedGoalsReversed := gs ++ updatedGoalsReversed
                    continue
                  else
                    throwError m! "try_apply failed {after}"
              | g_one :: g_last :: rest_rev => do
                  setGoals [g_last]
                  evalTactic (← `(tactic| try_apply_lemma_hyps [$[$hs],*]))

                  let after ← getGoals

                  if after.isEmpty then
                    setGoals ( [g_one ] ++ rest_rev )
                    progress := true
                    handled := true
                    let gs <- getGoals
                    updatedGoalsReversed := gs ++ updatedGoalsReversed

                    continue
                  else
                    logInfo "try_apply_lemma_hyps: recursive call did not solve the isolated modulus-bound goal"
                    throwError m! "try_apply failed {after}"
        catch e =>
              pure ()

      if progress then
          continue
      let loopBodyResult ← (ContT.run · pure) $ MonadCont.callCC $ fun loopBodyReturn => do
        if args.size > 3 then
          let g ← getMainGoal
          let goalType ← g.getType
          let e ← instantiateMVars goalType
          let args := e.getAppArgs
          handleIfMux loopBodyReturn g args

          if ((terms.size = 2))  && ( (← containsSub instantiatedGoalType) ||  bothArgsAreApps instantiatedGoalType )  then
             caseByCaseOnTwoVariables loopBodyReturn g hyps terms
          if exprHasNestedIf instantiatedGoalType then
            let g <- getMainGoal
            logInfo m!"try_apply_lemma_hyps: splitting nested if-expression"
            try
              monadLift $ do evalTactic (← `(tactic| split_ifs))
              let g' <- getMainGoal

              if (← g.isAssigned)  then
                logInfo m!"try_apply_lemma_hyps: nested if split solved the focused goal {g}"
                return { didMux := false, madeProgress := true, goals := <- getGoals , leftSide := false, stopCompletely:= false}
            catch _ => pure ()
          if terms.size >= 1 then
            findAndApplyRangeAnalysisLemma loopBodyReturn terms g instantiatedGoalType hyps
          else
            let rfl ← monadLift (m := TacticM) ``(Nat.le_refl)
            let bitvec ← monadLift (m := TacticM) ``(BitVec.toNatLT)
            let modLemma ← monadLift (m := TacticM) ``(mod_le_pred)
            let (fn, args) := instantiatedGoalType.getAppFnArgs
            let unfolded := ← monadLift $ withTransparency .reducible (whnf args[2]!)
            let fn3 := unfolded.getAppFn
               match fn with
                  | ``LE.le =>
                      match fn3 with
                        | Expr.const name _ =>
                          match name with
                          | ``ZMod.val =>
                              applyZModLemma loopBodyReturn g  instantiatedGoalType false hyps
                          | ``BitVec.toNat =>
                              if exprHasMod instantiatedGoalType then
                                applyThisLemma loopBodyReturn g instantiatedGoalType false modLemma
                              else
                                 applyThisLemma loopBodyReturn g instantiatedGoalType false bitvec
                          | _ =>
                              if containsMVar instantiatedGoalType then
                                applyNatLeRefl2 loopBodyReturn g instantiatedGoalType false rfl
                              else
                                pure ()

                        | _ =>
                          if containsMVar instantiatedGoalType then
                              applyNatLeRefl2 loopBodyReturn g instantiatedGoalType false rfl
                          else
                              pure ()
                  | _ => pure ()

        if (terms.size = 0) && isIneq instantiatedGoalType then
          try
            monadLift $ do evalTactic (← `(tactic| decide))
            if ← g.isAssigned then
              return { didMux := false, madeProgress := true, goals := [g] , leftSide := false, stopCompletely:= false}
          catch _err =>
              return { didMux := false, madeProgress := false, goals := [g] , leftSide := false, stopCompletely:= true}

        try
          monadLift $ do evalTactic (← `(tactic|  focus
                  (split_ifs; all_goals simp ) ))
          if ← g.isAssigned then
            let mut gs <- getGoals
            return { didMux := false, madeProgress := true, goals := gs , leftSide :=false, stopCompletely:=false}
        catch _err => pure ()
        try
          monadLift $ do evalTactic (← `(tactic| exact 0 ) )
          if ← g.isAssigned then
            let mut gs <- getGoals
            return { didMux := false, madeProgress := true, goals := gs , leftSide :=false, stopCompletely:=false}
        catch _err => pure ()
        return { didMux := false, madeProgress := false, goals := [g], leftSide:=false, stopCompletely:= false }
      if loopBodyResult.didMux then
          did_mux := true
      if loopBodyResult.stopCompletely then stop_completely := true
      if loopBodyResult.madeProgress then do
        handled := true; progress := true
      if loopBodyResult.leftSide && !did_mux then
         let rev := loopBodyResult.goals
         let rev :=
            match rev with
            | a :: b :: rest => b :: a :: rest
            | _ =>
              rev
          updatedGoalsReversed :=  updatedGoalsReversed ++ rev.reverse
      else
        updatedGoalsReversed := loopBodyResult.goals.reverse ++ updatedGoalsReversed

    setGoals (updatedGoalsReversed.reverse ++ goalQueue.dList ++ goalQueue.eList.reverse)

end BVModEq
